# Generated by Django 2.0.5 on 2018-11-20 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractDate', models.DateField(auto_now_add=True)),
                ('tempMAX', models.FloatField(default=80)),
                ('tempMIN', models.FloatField(default=0)),
                ('hrMAX', models.FloatField(default=0)),
                ('hrMIN', models.FloatField(default=0)),
                ('accMAX', models.FloatField(default=0)),
                ('accMIN', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
