# Generated by Django 2.0.5 on 2018-11-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='accMAX',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hrMAX',
            field=models.FloatField(default=100),
        ),
    ]
